# Set up the Rust toolchain.
language: rust
rust:
    - nightly

# Since this build doesn't require sudo, we can turn it off and improve build
# performance.
sudo: false

# Force third-party crates to persist from previous builds and update only when
# needed.
cache: cargo

# Install the necessary crates for building and testing the engine.
before_script:
    - export PATH=$PATH:/home/travis/.cargo/bin
    - (cargo install cargo-local-pkgs || true)
    - (cargo install rustfmt || true)

# Run tests and benchmarks.
script: cargo test -p rasen -p rasen-dsl && cargo bench -p rasen -p rasen-dsl
