# Set up the build environment.
environment:
    matrix:
        - channel: nightly
          target: x86_64-pc-windows-msvc

# Set up the Rust toolchain.
install:
    - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
    - curl -fsS "https://win.rustup.rs/" -o rustup-init.exe
    - rustup-init.exe -y --default-toolchain %channel%-%target%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - rustc -V
    - cargo -V

# Force third-party crates to persist from previous builds and update only when
# needed.
cache:
    - .cargo -> rust-%channel%-date, cargo-%channel%-build

# Since this is not a .NET project, we can flip the build system off.
build: false

# Run tests and benchmarks.
test_script:
    - cargo test --all
    - cargo bench -p rasen
    - cargo bench -p rasen-dsl
