[package]
name = "rasen-codegen"
version = "0.1.0"
authors = ["l3ops <github@leops.me>"]

[lib]
proc-macro = true

[features]
default = []

[dependencies]
syn = "0.11.11"
quote = "0.3.15"
clippy = { version = "0.0.133", optional = true }
